[package]
name = "uni-asm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
lalrpop-util = { version = "0.20", features = ["lexer"] }
regex = "1"

[build-dependencies]
lalrpop = "0.20"
